version: '3.5'

services:

  postgresql:
    image: postgres:9.6
    container_name: addressbook_postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    expose:
      - "5432"

    restart: "no"


  application:
    container_name: addressbook_app
    image: farzadz/addressbook:v1.2
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://addressbook_postgresql:5432/postgres

    depends_on:
      - postgresql