#server:
#  port:
#    9090
#
#
#
### default connection pool
#spring:
#  jpa:
#    properties:
#      hibernate:
#        dialect: "org.hibernate.dialect.PostgreSQLDialect"
#        jpa:
#          hibernate.ddl-auto : none
#          show-sql: true
#  datasource:
#    hikari:
#      connectionTimeout: 20000
#      maximumPoolSize: 5
#
#    ## PostgreSQL
#    url: jdbc:postgresql://localhost:5440/postgres
#    username: "postgres"
#    password: "password"
spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:yourDB